### ISSUE TITLE
IDE support - async keyword in `html.Script`?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-html-components#54]
See community thread: https://community.plot.ly/t/error-running-dash-after-upgrade-of-plotly/12507/5?u=chriddyp

cc @rmarren1

**Comment by rmarren1** [comment]
It looks like the IDE support PR can not handle components which have arguments that are [Python Keywords](https://github.com/python/cpython/blob/292030354aaf362113c64a402094fc928c8441e0/Lib/keyword.py#L15-L53).

None of the core components have had these in 3.6, but that changed in 3.7.

The PR https://github.com/plotly/dash/pull/325 is a patch to fix this, namely it checks if each argument is in `keyword.kwlist`, and if it is Dash will accept that keyword via `**kwargs` rather than via a named argument.

**Comment by rmarren1** [comment]
See https://github.com/plotly/dash/issues/327
